# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeLearn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNativeLearn
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTText',
    'RCTImage',
    'RCTWebSocket',
    'RCTPushNotification',
    'RCTActionSheet',
    'ART',
    'RCTCameraRoll',
    'RCTAnimation',
    'RCTLinkingIOS'
  ]
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
end
